"""
Parameters for server
"""

# in bytes
CHUNK_SIZE = 1024
REQUEST_HEADER_SIZE = 23
RESPONSE_HEADER_SIZE = 7
PUB_KEY_SIZE = 160
MAX_ALLOWED_USERNAME = 255
UUID_SIZE = 16
MSG_TYPE_SIZE = 1
CONTENT_SIZE = 4
MSG_ID_SIZE = 4


SERVER_DB = 'server.db'
MAX_ACCEPTED_CONNECTIONS = 100

# register request
REGISTER_REQUEST_CODE = 1000
REGISTER_REQUEST_PAYLOAD = MAX_ALLOWED_USERNAME + PUB_KEY_SIZE
REGISTER_SUCCESS_STATUS = 2000  # successful registration

# clients list request
CLIENTS_LIST_REQUEST_CODE = 1001
CLIENTS_LIST_REQUEST_PAYLOAD = 0
CLIENTS_LIST_SUCCESS_STATUS = 2001

# public key request
PUBLIC_KEY_REQUEST_CODE = 1002
PUBLIC_KEY_REQUEST_PAYLOAD = UUID_SIZE
PUBLIC_KEY_SUCCESS_STATUS = 2002

# sending messages
SEND_MESSAGE_REQUEST_CODE = 1003
SEND_MESSAGE_SUCCESS_STATUS = 2003

# pulling waiting messages
WAITING_MESSAGES_REQUEST_CODE = 1004
WAITING_MESSAGES_SUCCESS_STATUS = 2004

# message types
SYMMETRIC_KEY_REQUEST_MSG_TYPE = 1
SYMMETRIC_KEY_SEND_MSG_TYPE = 2
TEXT_SEND_MSG_TYPE = 3
FILE_SEND_MSG_TYPE = 4


SERVER_ERROR_CODE = 9000
SERVER_ERROR_SIZE = 0
